AWSTemplateFormatVersion: '2010-09-09'
Description: Pre-deployment requirements for DoCaaS devlabs

Resources:
  #CLOUD9 Instance
  TheCloud9Instance:
    Type: AWS::Cloud9::EnvironmentEC2
    Properties:
      Description: Cloud 9 IDE for Securing Saas Applications Built on Serverless Microservices DevLab
      InstanceType: t2.large
      Name: Securing Saas Applications Built on Serverless Microservices
  #ACM Certificate

