AWSTemplateFormatVersion: '2010-09-09'
Description: Pre-deployment requirements for DoCaaS devlabs

Resources:
  #S3 Bucket
  DeploymentBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Delete
    Properties:
      BucketName: !Sub '${AWS::AccountId}-docaas-devlab'
      BucketEncryption:
        ServerSideEncryptionConfiguration: 
          -
            ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256

  #ROUTE53 Hosted Zone
  HostedZone: 
    Type: "AWS::Route53::HostedZone"
    Properties: 
      Name: !Sub '${AWS::AccountId}.docaas.net.'

Outputs:
  DomainName:
    Value: !Sub '${AWS::AccountId}.docaas.net'
  HostedZoneNameServers:
    Value: !Join
        - ', '
        - !GetAtt [HostedZone, NameServers]