// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:d95781b7-074d-453c-a008-8617176fd2d7",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_eW8EtaIWr",
    "aws_user_pools_web_client_id": "4bc17f6cb4q0t9aln4etr1gc07"
};


export default awsmobile;
