// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "ap-southeast-2",
    "aws_cognito_identity_pool_id": "ap-southeast-2:a007fc81-bbcb-49a0-8df3-c50996c580f4",
    "aws_cognito_region": "ap-southeast-2",
    "aws_user_pools_id": "ap-southeast-2_ZORvRqoxr",
    "aws_user_pools_web_client_id": "jh5r2ffbao4nvun7feejbbtsc"
};


export default awsmobile;
